//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxtaPark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employes()
        {
            this.HistoryEnter = new HashSet<HistoryEnter>();
        }
    
        public int id_Emp { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Patronyme { get; set; }
        public Nullable<int> id_pos { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryEnter> HistoryEnter { get; set; }
    }
}
