//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxtaPark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEnter
    {
        public int id_History { get; set; }
        public Nullable<int> id_Emplo { get; set; }
        public Nullable<System.DateTime> datetimehistory { get; set; }
        public string typeentry { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
