//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxtaPark.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OxtaPark3Entities : DbContext
    {
        public OxtaPark3Entities()
            : base("name=OxtaPark3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employes> Employes { get; set; }
        public virtual DbSet<HistoryEnter> HistoryEnter { get; set; }
        public virtual DbSet<Orderr> Orderr { get; set; }
        public virtual DbSet<OrderService> OrderService { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
    }
}
