//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxtaPark.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int id_OrderServ { get; set; }
        public Nullable<int> id_Order { get; set; }
        public Nullable<int> id_Servic { get; set; }
    
        public virtual Orderr Orderr { get; set; }
        public virtual Service Service { get; set; }
    }
}
